### PR TITLE
Add API functions for `hostinfo`, `instanceinfo` and `serverinfo`

### PR DESCRIPTION
**Pull request by Sebbo94BY**
Adds various new read-only API functions:
- `hostinfo`
- `instanceinfo`
- `serverinfo`

### CODE REVIEW

**Comment by Murgeye** [comment]
Hi,
thanks for adding this.

Note that I will not update the PIP version for this for now, since you can already call these functions the same way using the default wrapper. But it's always nice to have more explicitly implemented commands.

**Comment by Sebbo94BY** [comment]
You're welcome!

Ok, but why don't you update the pip version? Are you planning a new release in the future - with more changes? Or which background has this decission?

I mean, for me it's currently fine (I think) as it's implemented as Git submodule in your bot: https://github.com/Murgeye/teamspeak3-python-bot/blob/main/.gitmodules

btw: Really awesome work with the bot! I really like the implementation and how it is working. Especially with the modules/plugin logic, that everyone can extend its features. :heart:

**Comment by Murgeye** [comment]
Hey, thanks for the praise 😅

To be honest I am just lazy and have to remember how to push new versions to pip each time. I should probably do it anyway to keep it in sync, even though this commit does not change anything in the usage of the API (as I said you could always call unimplemented commands anyway, you just have no python documentation for them).

I will probably do it in a few days if I find the time.

Thanks again!

**Comment by Sebbo94BY** [comment]
Ah, ok. Haha :D

Yeah, maybe it's possible to automate publishing new pip versions using e.g. Git workflows. Not sure. I've never published a pip package. 😅

**Pull request merged**
